# Generated by Django 2.2.12 on 2024-04-28 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catagory', '0001_initial'),
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TimeField()),
                ('Author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authors.Author')),
                ('Category', models.ManyToManyField(to='catagory.Category')),
            ],
        ),
    ]
