# Generated by Django 4.2.11 on 2024-04-27 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('roll', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('fname', models.CharField(max_length=20)),
                ('address', models.TextField()),
            ],
        ),
    ]
